services:
  - type: web
    name: alanrampacek-web
    runtime: python
    plan: free
    rootDir: website
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 3 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.5
    autoDeploy: true
